name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - name: check out rg-db-public
        uses: actions/checkout@v3
        with:
          # make sure rg-db-public is at the same level as rg-db-local in the
          # directory tree
          path: rg-db-public

      - name: check out regolith
        uses: actions/checkout@v3
        with:
          repository: regro/regolith
          # for bookkeeping have regolith at the same level as everything else in the
          # directory tree
          path: regolith

      - name: initialize miniconda
        # this uses a marketplace action that sets up miniconda in a way that makes
        # it easier to use.  I tried setting it up without this and it was a pain
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          # environment.yml file is needed by this action.  Because I don't want
          # maintain this but rather maintain the requirements files it just has
          # basic things in it like conda and pip
          environment-file: rg-db-public/environment.yml
          python-version: 3
          auto-activate-base: false

      - name: install regolith requirements
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          cd regolith
          conda install --file requirements/run.txt
          pip install -r requirements/pip.txt
          pip install .

      - name: Validate rg-db-public
        shell: bash -l {0}
        run: |
          cd rg-db-public/local
          conda activate test
          regolith validate
          regolith build publist --no-pdf
          regolith build cv --no-pdf
          regolith build html
          regolith build preslist --no-pdf
