name: Tests on PR

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest
    steps:
      - name: Check out rg-db-public repository
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.11

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: Install libgtk for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Install regolith and requirements
        run: |
          conda install --file requirements/test.txt
          conda install --file requirements/conda.txt
          pip install gooey
          python -m pip install . --no-deps

      - name: Validate rg-db-public
        shell: bash -l {0}
        run: |
          cd rg-db-public/local
          conda activate test
          regolith validate
          regolith build publist --no-pdf
          regolith build cv --no-pdf
          regolith build html
          regolith build preslist --no-pdf
